-- =========================================================
-- E-COMMERCE DATABASE
-- PostgreSQL
-- =========================================================

-- =========================================================
-- DROP OLD TABLES
-- WARNING: development only - deletes existing tables/data
-- =========================================================

DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS user_address CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- =========================================================
-- 1. USERS
-- =========================================================

CREATE TABLE users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email VARCHAR(50) NOT NULL UNIQUE,

    password VARCHAR(120) NOT NULL,

    username VARCHAR(20) NOT NULL UNIQUE
);


-- =========================================================
-- 2. ROLES
-- =========================================================

CREATE TABLE roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    role_name VARCHAR(30) NOT NULL UNIQUE
);


-- =========================================================
-- 3. USER_ROLE
-- Many-To-Many
-- =========================================================

CREATE TABLE user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id)
            REFERENCES users(user_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id)
            REFERENCES roles(role_id)
            ON DELETE CASCADE
);


-- =========================================================
-- 4. ADDRESSES
-- =========================================================

CREATE TABLE addresses
(
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    building_name VARCHAR(255),

    city VARCHAR(255) NOT NULL,

    country VARCHAR(255) NOT NULL,

    pincode VARCHAR(20),

    state VARCHAR(255),

    street VARCHAR(255)
);


-- =========================================================
-- 5. USER_ADDRESS
-- Many-To-Many
-- =========================================================

CREATE TABLE user_address
(
    user_id BIGINT NOT NULL,
    address_id BIGINT NOT NULL,

    PRIMARY KEY (user_id, address_id),

    CONSTRAINT fk_user_address_user
        FOREIGN KEY (user_id)
            REFERENCES users(user_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_user_address_address
        FOREIGN KEY (address_id)
            REFERENCES addresses(address_id)
            ON DELETE CASCADE
);


-- =========================================================
-- 6. CATEGORIES
-- =========================================================

CREATE TABLE categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_name VARCHAR(255) NOT NULL UNIQUE
);


-- =========================================================
-- 7. PRODUCTS
-- =========================================================

CREATE TABLE products
(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    description VARCHAR(255),

    discount NUMERIC(5,2) DEFAULT 0,

    image VARCHAR(255),

    price NUMERIC(12,2) NOT NULL,

    product_name VARCHAR(255) NOT NULL,

    quantity INT NOT NULL DEFAULT 0,

    special_price NUMERIC(12,2),

    category_id BIGINT NOT NULL,

    seller_id BIGINT NOT NULL,

    CONSTRAINT chk_product_price
        CHECK (price >= 0),

    CONSTRAINT chk_product_quantity
        CHECK (quantity >= 0),

    CONSTRAINT chk_product_discount
        CHECK (discount >= 0 AND discount <= 100),

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
            REFERENCES categories(category_id),

    CONSTRAINT fk_product_seller
        FOREIGN KEY (seller_id)
            REFERENCES users(user_id)
);


-- =========================================================
-- 8. CARTS
-- =========================================================

CREATE TABLE carts
(
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    total_price NUMERIC(12,2) NOT NULL DEFAULT 0,

    user_id BIGINT NOT NULL UNIQUE,

    CONSTRAINT fk_cart_user
        FOREIGN KEY (user_id)
            REFERENCES users(user_id)
            ON DELETE CASCADE
);


-- =========================================================
-- 9. CART_ITEMS
-- =========================================================

CREATE TABLE cart_items
(
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    discount NUMERIC(5,2) DEFAULT 0,

    product_price NUMERIC(12,2) NOT NULL,

    quantity INT NOT NULL,

    cart_id BIGINT NOT NULL,

    product_id BIGINT NOT NULL,

    CONSTRAINT chk_cart_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT fk_cart_item_cart
        FOREIGN KEY (cart_id)
            REFERENCES carts(cart_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_cart_item_product
        FOREIGN KEY (product_id)
            REFERENCES products(product_id),

    CONSTRAINT uq_cart_product
        UNIQUE (cart_id, product_id)
);


-- =========================================================
-- 10. PAYMENTS
-- =========================================================

CREATE TABLE payments
(
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payment_method VARCHAR(255) NOT NULL
);


-- =========================================================
-- 11. ORDERS
-- =========================================================

CREATE TABLE orders
(
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email VARCHAR(255) NOT NULL,

    order_date DATE NOT NULL,

    order_status VARCHAR(50) NOT NULL,

    total_amount NUMERIC(12,2) NOT NULL,

    payment_id BIGINT,

    user_id BIGINT NOT NULL,

    CONSTRAINT chk_order_amount
        CHECK (total_amount >= 0),

    CONSTRAINT fk_order_payment
        FOREIGN KEY (payment_id)
            REFERENCES payments(payment_id),

    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id)
            REFERENCES users(user_id)
);


-- =========================================================
-- 12. ORDER_ITEMS
-- =========================================================

CREATE TABLE order_items
(
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    discount NUMERIC(5,2) DEFAULT 0,

    ordered_product_price NUMERIC(12,2) NOT NULL,

    quantity INT NOT NULL,

    order_id BIGINT NOT NULL,

    product_id BIGINT NOT NULL,

    CONSTRAINT chk_order_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
            REFERENCES orders(order_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id)
            REFERENCES products(product_id),

    CONSTRAINT uq_order_product
        UNIQUE (order_id, product_id)
);


-- =========================================================
-- INSERT SAMPLE DATA
-- =========================================================


-- =========================================================
-- USERS - 10 RECORDS
-- =========================================================
-- Passwords below are sample database data only.
-- When we create Spring Security registration, passwords
-- should be BCrypt encoded before storing.

INSERT INTO users (email, password, username)
VALUES
    ('sarin@gmail.com',   'Password123!', 'sarin'),
    ('dara@gmail.com',    'Password123!', 'dara'),
    ('sokha@gmail.com',   'Password123!', 'sokha'),
    ('vanna@gmail.com',   'Password123!', 'vanna'),
    ('piseth@gmail.com',  'Password123!', 'piseth'),
    ('sreypov@gmail.com', 'Password123!', 'sreypov'),
    ('ratha@gmail.com',   'Password123!', 'ratha'),
    ('sophy@gmail.com',   'Password123!', 'sophy'),
    ('nita@gmail.com',    'Password123!', 'nita'),
    ('makara@gmail.com',  'Password123!', 'makara');


-- =========================================================
-- ROLES - 10 RECORDS
-- =========================================================

INSERT INTO roles (role_name)
VALUES
    ('ADMIN'),
    ('CUSTOMER'),
    ('SELLER'),
    ('MANAGER'),
    ('SUPPORT'),
    ('STAFF'),
    ('MODERATOR'),
    ('WAREHOUSE'),
    ('ACCOUNTANT'),
    ('DELIVERY');


-- =========================================================
-- USER_ROLE - 10 RECORDS
-- =========================================================

INSERT INTO user_role (user_id, role_id)
VALUES
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 3),
    (5, 3),
    (6, 2),
    (7, 2),
    (8, 2),
    (9, 2),
    (10, 2);


-- =========================================================
-- ADDRESSES - 10 RECORDS
-- =========================================================

INSERT INTO addresses
(building_name, city, country, pincode, state, street)
VALUES
    ('Building A', 'Phnom Penh', 'Cambodia', '12000', 'Phnom Penh', 'Street 271'),
    ('Building B', 'Phnom Penh', 'Cambodia', '12001', 'Phnom Penh', 'Street 2004'),
    ('House 10', 'Kampot', 'Cambodia', '07000', 'Kampot', 'National Road 3'),
    ('House 22', 'Siem Reap', 'Cambodia', '17000', 'Siem Reap', 'Sivutha Road'),
    ('Building C', 'Battambang', 'Cambodia', '02000', 'Battambang', 'Street 1'),
    ('House 7', 'Kandal', 'Cambodia', '08000', 'Kandal', 'National Road 2'),
    ('Building D', 'Takeo', 'Cambodia', '21000', 'Takeo', 'Street 12'),
    ('House 9', 'Kep', 'Cambodia', '23000', 'Kep', 'Beach Road'),
    ('Building E', 'Kampong Cham', 'Cambodia', '03000', 'Kampong Cham', 'Street 7'),
    ('House 15', 'Preah Sihanouk', 'Cambodia', '18000', 'Sihanoukville', 'Ekareach Street');


-- =========================================================
-- USER_ADDRESS - 10 RECORDS
-- =========================================================

INSERT INTO user_address (user_id, address_id)
VALUES
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
    (9, 9),
    (10, 10);


-- =========================================================
-- CATEGORIES - 10 RECORDS
-- =========================================================

INSERT INTO categories (category_name)
VALUES
    ('Laptops'),
    ('Smartphones'),
    ('Electronics'),
    ('Televisions'),
    ('Men Fashion'),
    ('Women Fashion'),
    ('Shoes'),
    ('Books'),
    ('Home Appliances'),
    ('Sports');


-- =========================================================
-- PRODUCTS - 10 RECORDS
-- =========================================================

INSERT INTO products
(
    description,
    discount,
    image,
    price,
    product_name,
    quantity,
    special_price,
    category_id,
    seller_id
)
VALUES
    (
        'Powerful laptop for development',
        10,
        'laptop-pro.jpg',
        1200.00,
        'Laptop Pro',
        15,
        1080.00,
        1,
        3
    ),
    (
        'High performance gaming laptop',
        5,
        'gaming-laptop.jpg',
        1500.00,
        'Gaming Laptop',
        10,
        1425.00,
        1,
        3
    ),
    (
        'Latest generation smartphone',
        5,
        'smartphone-x.jpg',
        799.00,
        'Smartphone X',
        30,
        759.05,
        2,
        4
    ),
    (
        'Bluetooth wireless headphones',
        0,
        'headphones.jpg',
        149.00,
        'Wireless Headphones',
        40,
        149.00,
        3,
        4
    ),
    (
        '55 inch 4K Smart Television',
        10,
        'smart-tv.jpg',
        999.00,
        'Smart TV 55',
        12,
        899.10,
        4,
        5
    ),
    (
        'Comfortable mens jacket',
        0,
        'jacket.jpg',
        89.99,
        'Mens Jacket',
        25,
        89.99,
        5,
        5
    ),
    (
        'Premium women handbag',
        0,
        'handbag.jpg',
        129.50,
        'Women Handbag',
        20,
        129.50,
        6,
        6
    ),
    (
        'Lightweight running shoes',
        5,
        'running-shoes.jpg',
        110.00,
        'Running Shoes',
        50,
        104.50,
        7,
        6
    ),
    (
        'Java programming beginner book',
        0,
        'java-book.jpg',
        45.75,
        'Java Programming Book',
        100,
        45.75,
        8,
        7
    ),
    (
        'Automatic coffee maker',
        10,
        'coffee-maker.jpg',
        79.99,
        'Coffee Maker',
        22,
        71.99,
        9,
        7
    );


-- =========================================================
-- CARTS - 10 RECORDS
-- =========================================================

INSERT INTO carts (total_price, user_id)
VALUES
    (799.00, 1),
    (298.00, 2),
    (79.99, 3),
    (110.00, 4),
    (179.98, 5),
    (137.25, 6),
    (1200.00, 7),
    (129.50, 8),
    (999.00, 9),
    (1500.00, 10);


-- =========================================================
-- CART_ITEMS - 10 RECORDS
-- =========================================================

INSERT INTO cart_items
(discount, product_price, quantity, cart_id, product_id)
VALUES
    (0, 799.00, 1, 1, 3),
    (0, 149.00, 2, 2, 4),
    (0, 79.99, 1, 3, 10),
    (0, 110.00, 1, 4, 8),
    (0, 89.99, 2, 5, 6),
    (0, 45.75, 3, 6, 9),
    (0, 1200.00, 1, 7, 1),
    (0, 129.50, 1, 8, 7),
    (0, 999.00, 1, 9, 5),
    (0, 1500.00, 1, 10, 2);


-- =========================================================
-- PAYMENTS - 10 RECORDS
-- =========================================================

INSERT INTO payments (payment_method)
VALUES
    ('CASH'),
    ('KHQR'),
    ('VISA'),
    ('MASTERCARD'),
    ('ABA_PAY'),
    ('ACLEDA_PAY'),
    ('WING'),
    ('PAYPAL'),
    ('BANK_TRANSFER'),
    ('CASH_ON_DELIVERY');


-- =========================================================
-- ORDERS - 10 RECORDS
-- =========================================================

INSERT INTO orders
(
    email,
    order_date,
    order_status,
    total_amount,
    payment_id,
    user_id
)
VALUES
    (
        'sarin@gmail.com',
        '2026-08-01',
        'COMPLETED',
        1200.00,
        1,
        1
    ),
    (
        'dara@gmail.com',
        '2026-08-02',
        'COMPLETED',
        1598.00,
        2,
        2
    ),
    (
        'sokha@gmail.com',
        '2026-08-03',
        'SHIPPED',
        149.00,
        3,
        3
    ),
    (
        'vanna@gmail.com',
        '2026-08-04',
        'PROCESSING',
        159.98,
        4,
        4
    ),
    (
        'piseth@gmail.com',
        '2026-08-05',
        'PENDING',
        110.00,
        5,
        5
    ),
    (
        'sreypov@gmail.com',
        '2026-08-06',
        'COMPLETED',
        269.97,
        6,
        6
    ),
    (
        'ratha@gmail.com',
        '2026-08-07',
        'SHIPPED',
        91.50,
        7,
        7
    ),
    (
        'sophy@gmail.com',
        '2026-08-08',
        'PROCESSING',
        999.00,
        8,
        8
    ),
    (
        'nita@gmail.com',
        '2026-08-09',
        'PENDING',
        129.50,
        9,
        9
    ),
    (
        'makara@gmail.com',
        '2026-08-10',
        'COMPLETED',
        1500.00,
        10,
        10
    );


-- =========================================================
-- ORDER_ITEMS - 10 RECORDS
-- =========================================================

INSERT INTO order_items
(
    discount,
    ordered_product_price,
    quantity,
    order_id,
    product_id
)
VALUES
    (0, 1200.00, 1, 1, 1),
    (0, 799.00, 2, 2, 3),
    (0, 149.00, 1, 3, 4),
    (0, 79.99, 2, 4, 10),
    (0, 110.00, 1, 5, 8),
    (0, 89.99, 3, 6, 6),
    (0, 45.75, 2, 7, 9),
    (0, 999.00, 1, 8, 5),
    (0, 129.50, 1, 9, 7),
    (0, 1500.00, 1, 10, 2);


-- =========================================================
-- CHECK DATA
-- =========================================================

SELECT 'users' AS table_name, COUNT(*) AS total FROM users
UNION ALL
SELECT 'roles', COUNT(*) FROM roles
UNION ALL
SELECT 'user_role', COUNT(*) FROM user_role
UNION ALL
SELECT 'addresses', COUNT(*) FROM addresses
UNION ALL
SELECT 'user_address', COUNT(*) FROM user_address
UNION ALL
SELECT 'categories', COUNT(*) FROM categories
UNION ALL
SELECT 'products', COUNT(*) FROM products
UNION ALL
SELECT 'carts', COUNT(*) FROM carts
UNION ALL
SELECT 'cart_items', COUNT(*) FROM cart_items
UNION ALL
SELECT 'payments', COUNT(*) FROM payments
UNION ALL
SELECT 'orders', COUNT(*) FROM orders
UNION ALL
SELECT 'order_items', COUNT(*) FROM order_items;