CREATE TABLE product_variants (
    variant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(100),
    size VARCHAR(100),
    color VARCHAR(100),
    price NUMERIC(12, 2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    image VARCHAR(255),
    product_id BIGINT NOT NULL,
    CONSTRAINT chk_product_variant_price CHECK (price >= 0),
    CONSTRAINT chk_product_variant_quantity CHECK (quantity >= 0),
    CONSTRAINT fk_product_variant_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE INDEX idx_product_variants_product_id
    ON product_variants(product_id);
